In [ ]:
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
import time
import pandas as pd

options = Options()
options.add_argument("--headless")
options.add_argument("--disable-gpu")
options.add_argument("--no-sandbox")
options.add_argument("user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36")
driver = webdriver.Chrome(options=options)

base_url = "https://www.flipkart.com/redmi-6-black-64-gb/product-reviews/itm3b52cae7d753e?pid=MOBFA2NXDQFTXNHJ"

reviews, ratings = [], []

for page in range(1, 100):  # scrape 10 halaman
    url = base_url + f"&page={page}"
    driver.get(url)
    time.sleep(2)

    review_blocks = driver.find_elements(By.CLASS_NAME, "col.EPCmJX.Ma1fCG")
    if not review_blocks:
        print(f"❌ Halaman {page} kosong atau diblok!")
        continue

    for block in review_blocks:
        try:
            rating = block.find_element(By.CLASS_NAME, "XQDdHH").text.strip()
            comment = block.find_element(By.CLASS_NAME, "ZmyHeo").text.strip()
            ratings.append(rating)
            reviews.append(comment)
        except:
            continue

driver.quit()

df = pd.DataFrame({'rating': ratings, 'review': reviews})
df.to_csv("flipkart_redmi6_reviews_with_rating.csv", index=False, encoding='utf-8-sig')
print("✅ Selesai! Total review terkumpul:", len(df))

❌ Halaman 21 kosong atau diblok!
❌ Halaman 22 kosong atau diblok!
❌ Halaman 23 kosong atau diblok!
❌ Halaman 24 kosong atau diblok!
❌ Halaman 25 kosong atau diblok!
❌ Halaman 26 kosong atau diblok!
❌ Halaman 27 kosong atau diblok!
❌ Halaman 28 kosong atau diblok!
❌ Halaman 29 kosong atau diblok!
❌ Halaman 30 kosong atau diblok!
❌ Halaman 31 kosong atau diblok!
❌ Halaman 32 kosong atau diblok!
❌ Halaman 33 kosong atau diblok!
❌ Halaman 34 kosong atau diblok!
❌ Halaman 35 kosong atau diblok!
❌ Halaman 36 kosong atau diblok!
❌ Halaman 37 kosong atau diblok!
❌ Halaman 38 kosong atau diblok!
❌ Halaman 39 kosong atau diblok!
❌ Halaman 40 kosong atau diblok!
❌ Halaman 41 kosong atau diblok!
❌ Halaman 42 kosong atau diblok!
❌ Halaman 43 kosong atau diblok!
❌ Halaman 44 kosong atau diblok!
❌ Halaman 45 kosong atau diblok!
❌ Halaman 46 kosong atau diblok!
❌ Halaman 47 kosong atau diblok!
❌ Halaman 48 kosong atau diblok!
❌ Halaman 49 kosong atau diblok!
❌ Halaman 50 kosong atau diblok!
❌ Halaman 51 kosong atau diblok!
❌ Halaman 52 kosong atau diblok!
❌ Halaman 53 kosong atau diblok!
❌ Halaman 54 kosong atau diblok!
❌ Halaman 55 kosong atau diblok!
❌ Halaman 56 kosong atau diblok!
❌ Halaman 57 kosong atau diblok!
❌ Halaman 58 kosong atau diblok!
❌ Halaman 59 kosong atau diblok!
❌ Halaman 60 kosong atau diblok!
❌ Halaman 61 kosong atau diblok!
❌ Halaman 62 kosong atau diblok!
❌ Halaman 63 kosong atau diblok!
❌ Halaman 64 kosong atau diblok!
❌ Halaman 65 kosong atau diblok!
❌ Halaman 66 kosong atau diblok!
❌ Halaman 67 kosong atau diblok!
❌ Halaman 68 kosong atau diblok!
❌ Halaman 69 kosong atau diblok!
❌ Halaman 70 kosong atau diblok!
❌ Halaman 71 kosong atau diblok!
❌ Halaman 72 kosong atau diblok!
❌ Halaman 73 kosong atau diblok!
❌ Halaman 74 kosong atau diblok!
❌ Halaman 75 kosong atau diblok!
❌ Halaman 76 kosong atau diblok!
❌ Halaman 77 kosong atau diblok!
❌ Halaman 78 kosong atau diblok!
❌ Halaman 79 kosong atau diblok!
❌ Halaman 80 kosong atau diblok!
❌ Halaman 81 kosong atau diblok!
❌ Halaman 82 kosong atau diblok!
❌ Halaman 83 kosong atau diblok!
❌ Halaman 84 kosong atau diblok!
❌ Halaman 85 kosong atau diblok!
❌ Halaman 86 kosong atau diblok!
❌ Halaman 87 kosong atau diblok!
❌ Halaman 88 kosong atau diblok!
❌ Halaman 89 kosong atau diblok!
❌ Halaman 90 kosong atau diblok!
❌ Halaman 91 kosong atau diblok!
❌ Halaman 92 kosong atau diblok!
❌ Halaman 93 kosong atau diblok!
❌ Halaman 94 kosong atau diblok!
❌ Halaman 95 kosong atau diblok!
❌ Halaman 96 kosong atau diblok!
❌ Halaman 97 kosong atau diblok!
❌ Halaman 98 kosong atau diblok!
❌ Halaman 99 kosong atau diblok!
✅ Selesai! Total review terkumpul: 200

In [20]:

df = pd.read_csv('flipkart_redmi6_reviews_with_rating.csv')

In [21]:
df

     rating                                             review
0         1  1. phone is really awesome\n2. battery is arou...
1         1                                  Worst performance
2         1  Hello dear friend don't buy this product\nPoor...
3         1                                        Bad quality
4         1  Everything is good but battery backup little a...
..      ...                                                ...
195       1  battery is not good.\nsound low.\nhearing prob...
196       1                  very bad mobile phone on Flipkart
197       1                 Mobile Phone accessories defective
198       1                                   sounds not clear
199       1                    worst phone ever got in my life

[200 rows x 2 columns]

In [31]:
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
import time
import pandas as pd

options = Options()
options.add_argument("--headless")
options.add_argument("--disable-gpu")
options.add_argument("--no-sandbox")
options.add_argument("user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36")
driver = webdriver.Chrome(options=options)

base_url = "https://www.flipkart.com/redmi-6-black-64-gb/product-reviews/itm3b52cae7d753e?pid=MOBFA2NXDQFTXNHJ"

reviews, ratings = [], []

for page in range(1, 21):  # scrape 10 halaman
    url = base_url + f"&page={page}"
    driver.get(url)
    time.sleep(2)

    review_blocks = driver.find_elements(By.CLASS_NAME, "col.EPCmJX.Ma1fCG")
    if not review_blocks:
        print(f"❌ Halaman {page} kosong atau diblok!")
        continue

    for block in review_blocks:
        try:
            rating = block.find_element(By.CLASS_NAME, "XQDdHH").text.strip()
            comment = block.find_element(By.CLASS_NAME, "ZmyHeo").text.strip()
            ratings.append(rating)
            reviews.append(comment)
        except:
            continue

driver.quit()

df = pd.DataFrame({'rating': ratings, 'review': reviews})
df.to_csv("flipkart_redmi6_reviews_with_rating_positive.csv", index=False, encoding='utf-8-sig')
print("✅ Selesai! Total review terkumpul:", len(df))

✅ Selesai! Total review terkumpul: 200

In [1]:
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
import time
import pandas as pd

options = Options()
options.add_argument("--headless")
options.add_argument("--disable-gpu")
options.add_argument("--no-sandbox")
options.add_argument("user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36")
driver = webdriver.Chrome(options=options)

base_url = "https://www.flipkart.com/redmi-6-black-64-gb/product-reviews/itm3b52cae7d753e?pid=MOBFA2NXDQFTXNHJ&lid=LSTMOBFA2NXDQFTXNHJJCPXIE&aid=overall&certifiedBuyer=false&sortOrder=MOST_RECENT"

reviews, ratings = [], []

for page in range(1, 21):  # scrape 10 halaman
    url = base_url + f"&page={page}"
    driver.get(url)
    time.sleep(2)

    review_blocks = driver.find_elements(By.CLASS_NAME, "col.EPCmJX.Ma1fCG")
    if not review_blocks:
        print(f"❌ Halaman {page} kosong atau diblok!")
        continue

    for block in review_blocks:
        try:
            rating = block.find_element(By.CLASS_NAME, "XQDdHH").text.strip()
            comment = block.find_element(By.CLASS_NAME, "ZmyHeo").text.strip()
            ratings.append(rating)
            reviews.append(comment)
        except:
            continue

driver.quit()

df = pd.DataFrame({'rating': ratings, 'review': reviews})
df.to_csv("flipkart_redmi6_reviews_with_rating_test.csv", index=False, encoding='utf-8-sig')
print("✅ Selesai! Total review terkumpul:", len(df))

✅ Selesai! Total review terkumpul: 200

In [32]:

df = pd.read_csv('flipkart_redmi6_reviews_with_rating_positive.csv')

In [33]:
df

     rating                                             review
0         4                    nice mobile in this price range
1         4              overall good phone\nyou can go for it
2         4                          good mobile in this price
3         5  Really Guys Awseome Mobile In Redmi Mobiles @ ...
4         5                                          very nice
..      ...                                                ...
195       5  This Mobile Really Nice\nCamera, Battery Excel...
196       5  Display size is Vary good.\nideal display for ...
197       5  Hands on to the first ever BLACK REDMI 6. slee...
198       5                                  very good quality
199       5  Best👍dual camera📷❤😘battery performance is grea...

[200 rows x 2 columns]

In [34]:
df

     rating                                             review
0         4                    nice mobile in this price range
1         4              overall good phone\nyou can go for it
2         4                          good mobile in this price
3         5  Really Guys Awseome Mobile In Redmi Mobiles @ ...
4         5                                          very nice
..      ...                                                ...
195       5  This Mobile Really Nice\nCamera, Battery Excel...
196       5  Display size is Vary good.\nideal display for ...
197       5  Hands on to the first ever BLACK REDMI 6. slee...
198       5                                  very good quality
199       5  Best👍dual camera📷❤😘battery performance is grea...

[200 rows x 2 columns]

In [35]:
import pandas as pd
from transformers import pipeline

In [36]:
model = pipeline("sentiment-analysis", model="nlptown/bert-base-multilingual-uncased-sentiment")

# STEP 6: Prediksi sentimen dari kolom 'gabungan'
def map_label(label):
    rating = int(label[0])
    if rating >= 4:
        return 'positif'
    elif rating == 3:
        return 'netral'
    else:
        return 'negatif'

results = model(df['review'].astype(str).tolist(), truncation=True)

df['label_help'] = [map_label(r['label']) for r in results]

Device set to use cpu

In [37]:
df

     rating                                             review label_help
0         4                    nice mobile in this price range    positif
1         4              overall good phone\nyou can go for it    positif
2         4                          good mobile in this price    positif
3         5  Really Guys Awseome Mobile In Redmi Mobiles @ ...    negatif
4         5                                          very nice    positif
..      ...                                                ...        ...
195       5  This Mobile Really Nice\nCamera, Battery Excel...    positif
196       5  Display size is Vary good.\nideal display for ...    positif
197       5  Hands on to the first ever BLACK REDMI 6. slee...    positif
198       5                                  very good quality    positif
199       5  Best👍dual camera📷❤😘battery performance is grea...    positif

[200 rows x 3 columns]

In [40]:
df['rating'] = df['rating'].astype(float)

In [38]:
df.label_help.value_counts()

label_help
positif    175
netral      18
negatif      7
Name: count, dtype: int64

In [42]:
df_org = pd.read_csv('more_data.csv')
df_org

     Unnamed: 0                                            Comment  Rating
0             0  Another Midrange killer Smartphone by Xiaomi A...     4.0
1             1  vry small size mobile All ok but vry small siz...     3.0
2             2  Full display not working in all application. Q...     3.0
3             3  Value for Money Redmi has always have been the...     5.0
4             4  Not worth for the money worst product from MI....     2.0
..          ...                                                ...     ...
465         465  battery is not good.\nsound low.\nhearing prob...     1.0
466         466                  very bad mobile phone on Flipkart     1.0
467         467                 Mobile Phone accessories defective     1.0
468         468                                   sounds not clear     1.0
469         469                    worst phone ever got in my life     1.0

[470 rows x 3 columns]

In [41]:
df

     rating                                             review label_help
0       4.0                    nice mobile in this price range    positif
1       4.0              overall good phone\nyou can go for it    positif
2       4.0                          good mobile in this price    positif
3       5.0  Really Guys Awseome Mobile In Redmi Mobiles @ ...    negatif
4       5.0                                          very nice    positif
..      ...                                                ...        ...
195     5.0  This Mobile Really Nice\nCamera, Battery Excel...    positif
196     5.0  Display size is Vary good.\nideal display for ...    positif
197     5.0  Hands on to the first ever BLACK REDMI 6. slee...    positif
198     5.0                                  very good quality    positif
199     5.0  Best👍dual camera📷❤😘battery performance is grea...    positif

[200 rows x 3 columns]

In [43]:
import pandas as pd

# Filter df untuk hanya ambil yang netral
df_netral = df[df['label_help'] == 'netral']

# Gabungkan komentar dari df_org dan df_netral
comments = pd.concat([df_org['Comment'], df_netral['review']], ignore_index=True)

# Gabungkan rating dari df_org dan df_netral
ratings = pd.concat([df_org['Rating'], df_netral['rating']], ignore_index=True)

# Gabungkan ke DataFrame baru
df_new = pd.DataFrame({
    'Comment': comments,
    'Rating': ratings
})

In [45]:
df_new.to_csv('more_data.csv')

In [2]:
df

    rating                                             review
0        3                                               Good
1        3                                    Value for money
2        4                                               Good
3        3  Budget oriented phone,decent camera battery ba...
4        1                                  Worst performance
..     ...                                                ...
195      3                                         Nice phone
196      1                          It is the picture quality
197      4                                              Super
198      5                               Very nice 👍 thanks 👍
199      4                                       Ovaroll good

[200 rows x 2 columns]

In [3]:
df_pos = pd.read_csv('flipkart_redmi6_reviews_with_rating_positive.csv')
df_pos

     rating                                             review
0         4                    nice mobile in this price range
1         4              overall good phone\nyou can go for it
2         4                          good mobile in this price
3         5  Really Guys Awseome Mobile In Redmi Mobiles @ ...
4         5                                          very nice
..      ...                                                ...
195       5  This Mobile Really Nice\nCamera, Battery Excel...
196       5  Display size is Vary good.\nideal display for ...
197       5  Hands on to the first ever BLACK REDMI 6. slee...
198       5                                  very good quality
199       5  Best👍dual camera📷❤😘battery performance is grea...

[200 rows x 2 columns]

In [4]:
df_gab = pd.read_csv('more_data.csv')
df_gab

     Unnamed: 0                                            Comment  Rating
0             0  Another Midrange killer Smartphone by Xiaomi A...     4.0
1             1  vry small size mobile All ok but vry small siz...     3.0
2             2  Full display not working in all application. Q...     3.0
3             3  Value for Money Redmi has always have been the...     5.0
4             4  Not worth for the money worst product from MI....     2.0
..          ...                                                ...     ...
483         483  awesome phone in this buget .but display quali...     4.0
484         484  its good lovely performance camera not so good...     4.0
485         485    battery backup is not good otherwise it is good     4.0
486         486                                    average product     4.0
487         487  camera good\nbut battery🔋 charging slowly\nscr...     5.0

[488 rows x 3 columns]

In [5]:
import pandas as pd

# Gabungkan komentar dari df_org dan df_netral
comments = pd.concat([df_gab['Comment'], df_pos['review']], ignore_index=True)

# Gabungkan rating dari df_org dan df_netral
ratings = pd.concat([df_gab['Rating'], df_pos['rating']], ignore_index=True)

# Gabungkan ke DataFrame baru
df_new = pd.DataFrame({
    'Comment': comments,
    'Rating': ratings
})

In [35]:
df_gab

     Unnamed: 0                                            Comment  Rating
0             0  Another Midrange killer Smartphone by Xiaomi A...     4.0
1             1  vry small size mobile All ok but vry small siz...     3.0
2             2  Full display not working in all application. Q...     3.0
3             3  Value for Money Redmi has always have been the...     5.0
4             4  Not worth for the money worst product from MI....     2.0
..          ...                                                ...     ...
483         483  awesome phone in this buget .but display quali...     4.0
484         484  its good lovely performance camera not so good...     4.0
485         485    battery backup is not good otherwise it is good     4.0
486         486                                    average product     4.0
487         487  camera good\nbut battery🔋 charging slowly\nscr...     5.0

[488 rows x 3 columns]

In [7]:
df_new.drop_duplicates(inplace=True)

In [8]:
df_new

                                               Comment  Rating
0    Another Midrange killer Smartphone by Xiaomi A...     4.0
1    vry small size mobile All ok but vry small siz...     3.0
2    Full display not working in all application. Q...     3.0
3    Value for Money Redmi has always have been the...     5.0
4    Not worth for the money worst product from MI....     2.0
..                                                 ...     ...
683  This Mobile Really Nice\nCamera, Battery Excel...     5.0
684  Display size is Vary good.\nideal display for ...     5.0
685  Hands on to the first ever BLACK REDMI 6. slee...     5.0
686                                  very good quality     5.0
687  Best👍dual camera📷❤😘battery performance is grea...     5.0

[618 rows x 2 columns]

In [9]:
df_new.Rating.value_counts()

Rating
5.0    274
1.0    224
4.0     88
3.0     27
2.0      5
Name: count, dtype: int64

In [10]:
df_new.to_csv('more_data.csv')

In [13]:
df_ori = pd.read_csv('redmi6.csv', encoding='cp1252')
df_ori

,Review Title,Customer name,Rating,Date,Category,Comments,Useful
0,Another Midrange killer Smartphone by Xiaomi,Rishikumar Thakur,4.0 out of 5 stars,on 1 October 2018,Display,Another Midrange killer Smartphone by Xiaomi\n...,
1,vry small size mobile,Raza ji,3.0 out of 5 stars,on 15 September 2018,Others,All ok but vry small size mobile,7 people found this helpful
2,Full display not working in all application.,Vaibhav Patel,3.0 out of 5 stars,on 18 September 2018,Others,Quite good,7 people found this helpful
3,Value for Money,Amazon Customer,5.0 out of 5 stars,on 28 September 2018,Display,Redmi has always have been the the king of bud...,2 people found this helpful
4,Not worth for the money,Sudhakaran Wadakkancheri,2.0 out of 5 stars,on 18 September 2018,Others,worst product from MI. I am a hardcore fan of ...,6 people found this helpful
...,...,...,...,...,...,...,...
275,"Cemera quality,face unlock most important in t...",Rahul,5.0 out of 5 stars,on 19 September 2018,Others,"I like This Phone, Awesome look and design.\nI...",NaN
276,Mi is best phone,Sunil Soni,4.0 out of 5 stars,on 18 September 2018,Others,Product is avasome but invoice is note include...,NaN
277,Its a OK Phone,D.C.Padhi,3.0 out of 5 stars,on 15 September 2018,Battery,"Redmi Note4, Note5, now 6pro..It seems the old...",NaN
278,Redmi,Mahesh,5.0 out of 5 stars,on 21 September 2018,Others,I love mi,NaN
279,Not worth for the price.,Vinod,1.0 out of 5 stars,on 17 September 2018,Camera,Same old configurations with higher price.\nNo...,NaN

In [14]:
df_ori['rating_float'] = df_ori['Rating'].str.extract(r'(\d+(\.\d+)?)')[0].astype(float)
df_ori

,Review Title,Customer name,Rating,Date,Category,Comments,Useful,rating_float
0,Another Midrange killer Smartphone by Xiaomi,Rishikumar Thakur,4.0 out of 5 stars,on 1 October 2018,Display,Another Midrange killer Smartphone by Xiaomi\n...,,4.0
1,vry small size mobile,Raza ji,3.0 out of 5 stars,on 15 September 2018,Others,All ok but vry small size mobile,7 people found this helpful,3.0
2,Full display not working in all application.,Vaibhav Patel,3.0 out of 5 stars,on 18 September 2018,Others,Quite good,7 people found this helpful,3.0
3,Value for Money,Amazon Customer,5.0 out of 5 stars,on 28 September 2018,Display,Redmi has always have been the the king of bud...,2 people found this helpful,5.0
4,Not worth for the money,Sudhakaran Wadakkancheri,2.0 out of 5 stars,on 18 September 2018,Others,worst product from MI. I am a hardcore fan of ...,6 people found this helpful,2.0
...,...,...,...,...,...,...,...,...
275,"Cemera quality,face unlock most important in t...",Rahul,5.0 out of 5 stars,on 19 September 2018,Others,"I like This Phone, Awesome look and design.\nI...",NaN,5.0
276,Mi is best phone,Sunil Soni,4.0 out of 5 stars,on 18 September 2018,Others,Product is avasome but invoice is note include...,NaN,4.0
277,Its a OK Phone,D.C.Padhi,3.0 out of 5 stars,on 15 September 2018,Battery,"Redmi Note4, Note5, now 6pro..It seems the old...",NaN,3.0
278,Redmi,Mahesh,5.0 out of 5 stars,on 21 September 2018,Others,I love mi,NaN,5.0
279,Not worth for the price.,Vinod,1.0 out of 5 stars,on 17 September 2018,Camera,Same old configurations with higher price.\nNo...,NaN,1.0

In [17]:
df_ori['gabungan'] = df_ori['Review Title'].astype(str) + " " + df_ori['Comments'].astype(str)

In [18]:
df_ori

,Review Title,Customer name,Rating,Date,Category,Comments,Useful,rating_float,gabungan
0,Another Midrange killer Smartphone by Xiaomi,Rishikumar Thakur,4.0 out of 5 stars,on 1 October 2018,Display,Another Midrange killer Smartphone by Xiaomi\n...,,4.0,Another Midrange killer Smartphone by Xiaomi A...
1,vry small size mobile,Raza ji,3.0 out of 5 stars,on 15 September 2018,Others,All ok but vry small size mobile,7 people found this helpful,3.0,vry small size mobile All ok but vry small siz...
2,Full display not working in all application.,Vaibhav Patel,3.0 out of 5 stars,on 18 September 2018,Others,Quite good,7 people found this helpful,3.0,Full display not working in all application. Q...
3,Value for Money,Amazon Customer,5.0 out of 5 stars,on 28 September 2018,Display,Redmi has always have been the the king of bud...,2 people found this helpful,5.0,Value for Money Redmi has always have been the...
4,Not worth for the money,Sudhakaran Wadakkancheri,2.0 out of 5 stars,on 18 September 2018,Others,worst product from MI. I am a hardcore fan of ...,6 people found this helpful,2.0,Not worth for the money worst product from MI....
...,...,...,...,...,...,...,...,...,...
275,"Cemera quality,face unlock most important in t...",Rahul,5.0 out of 5 stars,on 19 September 2018,Others,"I like This Phone, Awesome look and design.\nI...",NaN,5.0,"Cemera quality,face unlock most important in t..."
276,Mi is best phone,Sunil Soni,4.0 out of 5 stars,on 18 September 2018,Others,Product is avasome but invoice is note include...,NaN,4.0,Mi is best phone Product is avasome but invoic...
277,Its a OK Phone,D.C.Padhi,3.0 out of 5 stars,on 15 September 2018,Battery,"Redmi Note4, Note5, now 6pro..It seems the old...",NaN,3.0,"Its a OK Phone Redmi Note4, Note5, now 6pro..I..."
278,Redmi,Mahesh,5.0 out of 5 stars,on 21 September 2018,Others,I love mi,NaN,5.0,Redmi I love mi
279,Not worth for the price.,Vinod,1.0 out of 5 stars,on 17 September 2018,Camera,Same old configurations with higher price.\nNo...,NaN,1.0,Not worth for the price. Same old configuratio...

In [26]:
import pandas as pd

# Gabungkan komentar dari df_org dan df_netral
comments = pd.concat([df_gab['Comment'], df_ori['gabungan']], ignore_index=True)

# Gabungkan rating dari df_org dan df_netral
ratings = pd.concat([df_gab['Rating'], df_ori['rating_float']], ignore_index=True)

# Gabungkan ke DataFrame baru
df_new = pd.DataFrame({
    'Comment': comments,
    'Rating': ratings
})

In [27]:
df_new

                                               Comment  Rating
0    Another Midrange killer Smartphone by Xiaomi A...     4.0
1    vry small size mobile All ok but vry small siz...     3.0
2    Full display not working in all application. Q...     3.0
3    Value for Money Redmi has always have been the...     5.0
4    Not worth for the money worst product from MI....     2.0
..                                                 ...     ...
763  Cemera quality,face unlock most important in t...     5.0
764  Mi is best phone Product is avasome but invoic...     4.0
765  Its a OK Phone Redmi Note4, Note5, now 6pro..I...     3.0
766                                    Redmi I love mi     5.0
767  Not worth for the price. Same old configuratio...     1.0

[768 rows x 2 columns]

In [33]:
df[df_new.Comment.duplicated()]

C:\Users\71486\AppData\Local\Temp\ipykernel_20236\1433699137.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df[df_new.Comment.duplicated()]

    rating                                             review
10       5                                               Nice
11       5              Very good mobile phone for normal use
12       5                                          Very nice
13       5                                                 Ok
14       4                                     Up to the mark
15       3                              Not for mens and pubg
16       5        Value for money\nBattery best all mi mobile
17       1                                        Bad quality
18       4                                       Overall good
19       5                                  Very strong phone
40       5                            This model is very good
41       5                                       Good product
42       4                                    Value for money
43       5     Still in july 2023, its working fanstastically
44       5  It's 2023 and I'm still using this phone since...
45       5           Best phone in this range on those times.
46       5       Great product by redmi. Power pack perfmance
47       5                                               Nice
48       5                                          Excellent
49       1                                      Battery issue
80       5                                               Best
100      4                                  Super mobile ☺️☺️
114      5                               Awesome mind blowing
116      4                                       Good product
137      3                                        Nice mobile
185      5                            Nice phone good quality

In [ ]:
df_new.drop_duplicates(inplace=True)

In [40]:
df_new.duplicated().value_counts()

False    444
True     324
Name: count, dtype: int64

In [36]:
df_wa = pd.read_csv('more_data.csv')

In [37]:
df_wa

     Unnamed: 0                                            Comment  Rating
0             0  Another Midrange killer Smartphone by Xiaomi A...     4.0
1             1  vry small size mobile All ok but vry small siz...     3.0
2             2  Full display not working in all application. Q...     3.0
3             3  Value for Money Redmi has always have been the...     5.0
4             4  Not worth for the money worst product from MI....     2.0
..          ...                                                ...     ...
613         683  This Mobile Really Nice\nCamera, Battery Excel...     5.0
614         684  Display size is Vary good.\nideal display for ...     5.0
615         685  Hands on to the first ever BLACK REDMI 6. slee...     5.0
616         686                                  very good quality     5.0
617         687  Best👍dual camera📷❤😘battery performance is grea...     5.0

[618 rows x 3 columns]

In [38]:
df_wa.Rating.value_counts()

Rating
5.0    274
1.0    224
4.0     88
3.0     27
2.0      5
Name: count, dtype: int64

In [41]:
import pandas as pd

# Gabungkan komentar dari df_org dan df_netral
comments = pd.concat([df_wa['Comment'], df_ori['gabungan']], ignore_index=True)

# Gabungkan rating dari df_org dan df_netral
ratings = pd.concat([df_wa['Rating'], df_ori['rating_float']], ignore_index=True)

# Gabungkan ke DataFrame baru
df_new = pd.DataFrame({
    'Comment': comments,
    'Rating': ratings
})

In [43]:
df_new.duplicated().value_counts()

False    618
True     280
Name: count, dtype: int64

In [44]:
df_new.drop_duplicates(inplace=True)

In [47]:
df_new

                                               Comment  Rating
0    Another Midrange killer Smartphone by Xiaomi A...     4.0
1    vry small size mobile All ok but vry small siz...     3.0
2    Full display not working in all application. Q...     3.0
3    Value for Money Redmi has always have been the...     5.0
4    Not worth for the money worst product from MI....     2.0
..                                                 ...     ...
613  This Mobile Really Nice\nCamera, Battery Excel...     5.0
614  Display size is Vary good.\nideal display for ...     5.0
615  Hands on to the first ever BLACK REDMI 6. slee...     5.0
616                                  very good quality     5.0
617  Best👍dual camera📷❤😘battery performance is grea...     5.0

[618 rows x 2 columns]

In [45]:
df_test = pd.read_csv('flipkart_redmi6_reviews_with_rating_test.csv')

In [46]:
df_test

     rating                                             review
0         3                                               Good
1         3                                    Value for money
2         4                                               Good
3         3  Budget oriented phone,decent camera battery ba...
4         1                                  Worst performance
..      ...                                                ...
195       3                                         Nice phone
196       1                          It is the picture quality
197       4                                              Super
198       5                               Very nice 👍 thanks 👍
199       4                                       Ovaroll good

[200 rows x 2 columns]

In [48]:
import pandas as pd

# Gabungkan komentar dari df_org dan df_netral
comments = pd.concat([df_new['Comment'], df_test['review']], ignore_index=True)

# Gabungkan rating dari df_org dan df_netral
ratings = pd.concat([df_new['Rating'], df_test['rating']], ignore_index=True)

# Gabungkan ke DataFrame baru
df_new = pd.DataFrame({
    'Comment': comments,
    'Rating': ratings
})

In [50]:
df_new.duplicated().value_counts()

False    731
True      87
Name: count, dtype: int64